In [4]:
import numpy as np
x=np.arange(1,10,2)
print(x)

[1 3 5 7 9]


In [2]:
x=np.random.rand(5)
print(x)

[0.7118292  0.06364929 0.47137142 0.40584414 0.21846072]


In [3]:
x=np.random.randint(1,6)
print(x)

4


In [2]:
import random
x=random.randrange(5,10)
print(x)

7


In [5]:
list1=[[1,2,3],[4,5,6],[7,8,9]]
my_matrix=np.array(list1)
print(my_matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
my_matrix.ndim

2

In [7]:
x=np.random.rand(2,3)
print(x)

[[0.19800479 0.82728812 0.75470574]
 [0.77350115 0.21180928 0.33481003]]


In [8]:
x=np.random.randn(5)
print(x)

[ 0.31753732  0.05860851 -0.4990359   1.19424282 -0.80297336]


In [9]:
x=np.random.randint(10,100,(2,7))
print(x)

[[53 92 98 49 93 45 50]
 [78 84 13 16 54 72 28]]


In [10]:
array=np.array([(1,2,3),(4,5,6)],dtype=float)

In [11]:
array

array([[1., 2., 3.],
       [4., 5., 6.]])

In [12]:
array.shape

(2, 3)

In [17]:
array=np.array([1,2,3],ndmin=3)

In [18]:
array

array([[[1, 2, 3]]])

In [20]:
array[0][0][1]

np.int64(2)

In [21]:
x=np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [24]:
x=np.ones([4,5])
print(x)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [25]:
x=np.full((4,5),4)
print(x)

[[4 4 4 4 4]
 [4 4 4 4 4]
 [4 4 4 4 4]
 [4 4 4 4 4]]


In [2]:
import numpy as np
x=np.linspace(10,30,15)
print(x)

[10.         11.42857143 12.85714286 14.28571429 15.71428571 17.14285714
 18.57142857 20.         21.42857143 22.85714286 24.28571429 25.71428571
 27.14285714 28.57142857 30.        ]


In [3]:
list1=[10,20,30,40,50]
array1=np.asarray(list1)
print(array1)
type(array1)


[10 20 30 40 50]


numpy.ndarray

In [18]:
x=np.random.randint(10,40,(3,4))
print(x)
print(x.max())
print(x.argmax())

[[34 16 12 19]
 [35 15 21 23]
 [16 32 35 17]]
35
4


In [7]:
x.dtype

dtype('int32')

In [8]:
x.size

12

In [9]:
x.ndim

2

In [10]:
x.shape

(3, 4)

In [12]:
my_array2=np.array([1,2])


In [13]:
my_array2.shape

(2,)

In [3]:
import numpy as np
a=np.random.randint(10,20,(3,3))
b=np.random.randint(10,20,(3,3))
print(a)
print(b)

[[12 19 15]
 [16 18 12]
 [10 14 19]]
[[12 13 19]
 [17 16 13]
 [13 12 17]]


In [4]:
print(a.sum(axis=0))

[38 51 46]


In [5]:
print(a.sum(axis=1))

[46 46 43]


In [24]:
a+b

array([[30, 30, 32],
       [27, 29, 24],
       [29, 28, 33]], dtype=int32)

In [25]:
a-b

array([[ 8, -4, -4],
       [-1,  5,  2],
       [ 7,  8,  3]], dtype=int32)

In [26]:
a*b

array([[209, 221, 252],
       [182, 204, 143],
       [198, 180, 270]], dtype=int32)

In [27]:
a.dot(b)

array([[545, 619, 695],
       [524, 555, 616],
       [648, 702, 792]], dtype=int32)

In [6]:
a.transpose()

array([[12, 16, 10],
       [19, 18, 14],
       [15, 12, 19]], dtype=int32)

In [9]:
import numpy as np
arr=np.random.randint(10,20,(4,3))
print(arr)

[[11 15 11]
 [19 11 13]
 [16 10 15]
 [14 17 18]]


In [10]:
arr.reshape(1,12)

array([[11, 15, 11, 19, 11, 13, 16, 10, 15, 14, 17, 18]], dtype=int32)

In [12]:
arr=np.arange(1,10)
arr[::]=9

In [13]:
arr

array([9, 9, 9, 9, 9, 9, 9, 9, 9])

In [15]:
arr=np.random.randint(100,199,(4,3))

In [16]:
arr

array([[187, 138, 141],
       [160, 197, 132],
       [119, 113, 108],
       [176, 189, 125]], dtype=int32)

In [17]:
print(arr[0,2])

141


In [18]:
print(arr[0:1,1:])

[[138 141]]


In [19]:
list1=[0,1,2,3,4,5,6,7,8,9]
filter_data=[]
for item in list1:
    if item>4:
        filter_data.append(item)

In [20]:
filter_data

[5, 6, 7, 8, 9]

In [24]:
arr=np.array(list1)

In [25]:
arr[arr>4]

array([5, 6, 7, 8, 9])

In [1]:
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
result=np.hstack((a,b))
print(result)

[1 2 3 4 5 6]


In [2]:
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
result=np.vstack((a,b))
print(result)

[[1 2 3]
 [4 5 6]]


In [8]:
import numpy as np
from time import process_time
list1=[i for i in range(10000000)]
start_time=process_time()
list1=[i+10 for i in list1]
end_time=process_time()
print(end_time-start_time)


1.765625


In [1]:
import numpy as np
from time import process_time
array1=np.array([i for i in range(1000000)])
start_time=process_time()
array1+=10
end_time=process_time()
print(end_time-start_time)
                

0.0


In [2]:
list1=[1,2,3,4,5]
print(list1)
print(type(list1))

[1, 2, 3, 4, 5]
<class 'list'>


In [3]:
array1=np.array([1,2,3,4])
print(array1)
print(type(array1))

[1 2 3 4]
<class 'numpy.ndarray'>


In [4]:
x=np.arange(1,10,2)
print(x)

[1 3 5 7 9]


In [5]:
x=np.random.rand(6)
print(x)

[0.06436864 0.46323527 0.21914229 0.24690035 0.74654816 0.10820833]


In [6]:
list1=([[1,2,3],[4,5,6],[7,8,9]])
my_matrix=np.array(list1)
print(my_matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
x=np.random.rand(2,3)
print(x)

[[0.03227011 0.69554477 0.17433526]
 [0.68092518 0.52116304 0.97743815]]


In [8]:
x=np.random.randn(5)
print(x)

[-1.28013381  0.40011037 -0.14849407  0.98607348  0.3128496 ]


In [9]:
x=np.random.randint(1,100,(3,4))
print(x)

[[39 42 19 32]
 [10 36 15 73]
 [90  1 61 61]]


In [12]:
array2=np.array([(1,2,3),(4,5,6)],dtype=float)
print(array2)


[[1. 2. 3.]
 [4. 5. 6.]]


In [18]:
array2=np.array([(1,2,3),(4,5,6)],ndmin=5)
print(array2)
print("no. of dimension",array2.ndim)

[[[[[1 2 3]
    [4 5 6]]]]]
no. of dimension 5


In [21]:
x=np.zeros((4,4))
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [22]:
x=np.ones((4,4))
print(x)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [23]:
x=np.full((4,4),5)
print(x)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [25]:
x=np.eye(3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [27]:
x=np.random.random((3,4))
print(x)

[[0.62605306 0.33990691 0.40669079 0.76587325]
 [0.4572658  0.80487286 0.31485714 0.10614229]
 [0.66118482 0.18162773 0.15321189 0.55555483]]


In [32]:
x=np.linspace(1,20,2)
print(x)

[ 1. 20.]


In [33]:
list1=[1,2,3,4]
ar=np.array(list1)
print(ar)

[1 2 3 4]


In [34]:
ar=np.sqrt(list1)
print(ar)

[1.         1.41421356 1.73205081 2.        ]


In [35]:
ar=np.sin(list1)
print(ar)

[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]


In [36]:
ar=np.log(list1)
print(ar)

[0.         0.69314718 1.09861229 1.38629436]


In [37]:
arr=np.random.randint(1,10,(3,4))
print(arr)

[[6 3 8 1]
 [3 9 7 2]
 [9 3 8 9]]


In [38]:
arr.max()

np.int32(9)

In [39]:
arr.min()

np.int32(1)

In [40]:
arr.argmin()

np.int64(3)

In [41]:
arr.argmax()

np.int64(5)

In [42]:
arr.mean()

np.float64(5.666666666666667)

In [43]:
arr.std()

np.float64(2.9249881291307074)

In [44]:
arr.var()

np.float64(8.555555555555555)

In [45]:
arr.sum(axis=0)

array([18, 15, 23, 12])

In [46]:
arr.sum(axis=1)

array([18, 21, 29])

In [47]:
trans=np.transpose(arr)
print(trans)

[[6 3 9]
 [3 9 3]
 [8 7 8]
 [1 2 9]]


In [ ]:
import multiprocessing

# Step 1: Define a simple function
def square_number(n):
    return n * n

if __name__ == "__main__":
    # Step 2: Create a list of numbers
    numbers = [1, 2, 3, 4, 5]

    # Step 3: Create a Pool of workers (parallel processes)
    with multiprocessing.Pool(processes=3) as pool:
        results = pool.map(square_number, numbers)

    # Step 4: Print results
    print("Input:", numbers)
    print("Output:", results)
